# Generated by Django 3.1.2 on 2020-10-31 12:30

import uuid

import django.db.models.deletion
import pydantic.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('uid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'event_type',
                    models.CharField(
                        choices=[('ss', 'Shift Start'), ('se', 'Shift End'), ('i', 'Incident')],
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now=True)),
                (
                    'data',
                    models.JSONField(null=True, validators=[pydantic.main.BaseModel.validate]),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    'sex',
                    models.CharField(
                        choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10
                    ),
                ),
                ('fio', models.TextField()),
                ('occupation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250, null=True)),
                (
                    'layout',
                    models.JSONField(null=True, validators=[pydantic.main.BaseModel.validate]),
                ),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                (
                    'config',
                    models.JSONField(null=True, validators=[pydantic.main.BaseModel.validate]),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sites',
                        to='server.organization',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'site',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='shift_reports',
                        to='server.site',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                (
                    'site',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='shifts',
                        to='server.site',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SensorReport',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('data', models.JSONField(validators=[pydantic.main.BaseModel.validate])),
                ('created_at', models.DateTimeField(auto_now=True)),
                (
                    'sensor',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reports',
                        to='server.sensor',
                    ),
                ),
                (
                    'site',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sensor_reports',
                        to='server.site',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='site',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sensors',
                to='server.site',
            ),
        ),
    ]
