# Generated by Django 3.1.2 on 2020-10-31 13:55

from django.db import migrations, models
import server.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreport',
            name='data',
            field=models.JSONField(validators=[server.models.validators.validate_sensor_report_data]),
        ),
        migrations.AlterField(
            model_name='site',
            name='config',
            field=models.JSONField(null=True, validators=[server.models.validators.validate_site_config]),
        ),
        migrations.AlterField(
            model_name='site',
            name='layout',
            field=models.JSONField(null=True, validators=[server.models.validators.validate_site_layout]),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='data',
            field=models.JSONField(null=True, validators=[server.models.validators.validate_site_event_data]),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='event_type',
            field=models.CharField(choices=[('shift_start', 'Shift Start'), ('shift_end', 'Shift End'), ('incident', 'Incident')], max_length=20),
        ),
    ]
