# Generated by Django 3.1.2 on 2020-10-31 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20201031_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='site',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='uid',
        ),
    ]
