# Generated by Django 3.1.2 on 2020-10-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20201031_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreport',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensorreport',
            name='uid',
            field=models.UUIDField(default='d894eb62-1f6c-4862-9157-f44539930146', editable=False),
            preserve_default=False,
        ),
    ]
