# Generated by Django 3.1.2 on 2020-10-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20201031_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='site',
            name='long',
        ),
        migrations.AddField(
            model_name='site',
            name='corners',
            field=models.JSONField(null=True),
        ),
    ]
