# Generated by Django 3.1.2 on 2020-11-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20201031_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreport',
            name='uid',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
