# Generated by Django 3.1.2 on 2020-11-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20201031_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreport',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensorreport',
            name='uid',
            field=models.UUIDField(default='1cdc06c4-0b80-4676-a714-9939791270e9', editable=False),
            preserve_default=False,
        ),
    ]
