# Generated by Django 3.1.2 on 2020-11-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20201101_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreport',
            name='uid',
            field=models.UUIDField(),
        ),
    ]
