# Generated by Django 3.1.2 on 2020-11-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20201101_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreport',
            name='data',
            field=models.JSONField(),
        ),
    ]
