# Generated by Django 3.1.2 on 2020-11-01 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20201101_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='time_point',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShiftReport',
        ),
    ]
